source 'https://rubygems.org'

ruby '2.3.1'
gem 'headless'
gem 'selenium-webdriver', '2.53.1'
gem 'watir-webdriver'
gem 'page-object'
gem 'cucumber'
gem 'rspec'
gem 'rspec-expectations'
gem 'rspec-wait'